// <auto-generated />
using System;
using LegalMateAI.DAL.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LegalMateAI.DAL.Migrations
{
    [DbContext(typeof(LegalMateDbContext))]
    [Migration("20251011114208_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LegalMateAI.Domain.Entities.AIModels", b =>
                {
                    b.Property<int>("ModelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModelID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ModelType")
                        .HasColumnType("int");

                    b.Property<string>("TrainedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ModelID");

                    b.ToTable("AIModels");
                });

            modelBuilder.Entity("LegalMateAI.Domain.Entities.Admin", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("AdminID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("LegalMateAI.Domain.Entities.AdminLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<int>("AdminID")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("EntityID")
                        .HasColumnType("int");

                    b.Property<string>("EntityName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("LogID");

                    b.HasIndex("AdminID");

                    b.HasIndex("Timestamp");

                    b.ToTable("AdminLogs");
                });

            modelBuilder.Entity("LegalMateAI.Domain.Entities.Articles", b =>
                {
                    b.Property<int>("ArticleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArticleID"));

                    b.Property<string>("ArticleNumber")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("LawID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArticleID");

                    b.HasIndex("LawID");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("LegalMateAI.Domain.Entities.ChatbotLog", b =>
                {
                    b.Property<int>("ChatID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChatID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Response")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ChatID");

                    b.HasIndex("UserID");

                    b.ToTable("ChatbotLogs");
                });

            modelBuilder.Entity("LegalMateAI.Domain.Entities.Clause", b =>
                {
                    b.Property<int>("ClauseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClauseID"));

                    b.Property<int>("ArticleID")
                        .HasColumnType("int");

                    b.Property<string>("ClauseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ClauseText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClauseID");

                    b.HasIndex("ArticleID");

                    b.ToTable("Clauses");
                });

            modelBuilder.Entity("LegalMateAI.Domain.Entities.Consultation", b =>
                {
                    b.Property<int>("ConsultationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsultationID"));

                    b.Property<int?>("AdminID")
                        .HasColumnType("int");

                    b.Property<string>("Answer")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("DateAnswer")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateAsked")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUrgent")
                        .HasColumnType("bit");

                    b.Property<int?>("LawyerID")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ConsultationID");

                    b.HasIndex("AdminID");

                    b.HasIndex("LawyerID");

                    b.HasIndex("Status");

                    b.HasIndex("UserID");

                    b.ToTable("Consultations");
                });

            modelBuilder.Entity("LegalMateAI.Domain.Entities.ContractsTemplate", b =>
                {
                    b.Property<int>("TemplateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TemplateID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TemplateID");

                    b.ToTable("ContractsTemplates");
                });

            modelBuilder.Entity("LegalMateAI.Domain.Entities.IRDocuments", b =>
                {
                    b.Property<int>("DocumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentID"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<byte[]>("EmbeddingVector")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("DocumentID");

                    b.HasIndex("UserID");

                    b.ToTable("IRDocuments");
                });

            modelBuilder.Entity("LegalMateAI.Domain.Entities.IRQueries", b =>
                {
                    b.Property<int>("QueryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QueryID"));

                    b.Property<byte[]>("EmbeddingVector")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("MatchedDocuments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("QueriedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("QueryText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("QueryID");

                    b.HasIndex("UserID");

                    b.ToTable("IRQueries");
                });

            modelBuilder.Entity("LegalMateAI.Domain.Entities.IRQueryDocument", b =>
                {
                    b.Property<int>("QueryID")
                        .HasColumnType("int");

                    b.Property<int>("DocumentID")
                        .HasColumnType("int");

                    b.HasKey("QueryID", "DocumentID");

                    b.HasIndex("DocumentID");

                    b.ToTable("IRQueryDocuments");
                });

            modelBuilder.Entity("LegalMateAI.Domain.Entities.Law", b =>
                {
                    b.Property<int>("LawID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LawID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IssuedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("IssuedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("LawID");

                    b.HasIndex("Category");

                    b.HasIndex("Title");

                    b.ToTable("Laws");
                });

            modelBuilder.Entity("LegalMateAI.Domain.Entities.LawUpdates", b =>
                {
                    b.Property<int>("UpdateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UpdateID"));

                    b.Property<int>("ChangeType")
                        .HasColumnType("int");

                    b.Property<int>("LawID")
                        .HasColumnType("int");

                    b.Property<string>("NewText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateSource")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("UpdateID");

                    b.HasIndex("LawID");

                    b.HasIndex("UpdateDate");

                    b.ToTable("LawUpdates");
                });

            modelBuilder.Entity("LegalMateAI.Domain.Entities.Lawyer", b =>
                {
                    b.Property<int>("LawyerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LawyerID"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("LawyerID");

                    b.ToTable("Lawyers");
                });

            modelBuilder.Entity("LegalMateAI.Domain.Entities.ModelResults", b =>
                {
                    b.Property<int>("ResultID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultID"));

                    b.Property<int>("AIModelModelID")
                        .HasColumnType("int");

                    b.Property<double?>("ConfidenceScore")
                        .HasColumnType("float");

                    b.Property<string>("InputData")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("ModelID")
                        .HasColumnType("int");

                    b.Property<string>("OutputData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ResultID");

                    b.HasIndex("AIModelModelID");

                    b.ToTable("ModelResults");
                });

            modelBuilder.Entity("LegalMateAI.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RedirectURL")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("NotificationID");

                    b.HasIndex("UserID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("LegalMateAI.Domain.Entities.SearchIndex", b =>
                {
                    b.Property<int>("IndexId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IndexId"));

                    b.Property<string>("Content")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<byte[]>("EmbeddingVector")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<int>("EntityType")
                        .HasColumnType("int");

                    b.Property<DateTime>("IndexedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Keywords")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("IndexId");

                    b.HasIndex("EntityId");

                    b.HasIndex("EntityType");

                    b.HasIndex("IndexedAt");

                    b.HasIndex("Keywords");

                    b.ToTable("SearchIndices");
                });

            modelBuilder.Entity("LegalMateAI.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LegalMateAI.Domain.Entities.UserContracts", b =>
                {
                    b.Property<int>("UserContractID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserContractID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilledData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FilledDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PdfUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TemplateID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("UserContractID");

                    b.HasIndex("TemplateID");

                    b.HasIndex("UserID");

                    b.ToTable("UserContracts");
                });

            modelBuilder.Entity("LegalMateAI.Domain.Entities.AdminLog", b =>
                {
                    b.HasOne("LegalMateAI.Domain.Entities.Admin", "Admin")
                        .WithMany("AdminLogs")
                        .HasForeignKey("AdminID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("LegalMateAI.Domain.Entities.Articles", b =>
                {
                    b.HasOne("LegalMateAI.Domain.Entities.Law", "Law")
                        .WithMany("LawArticles")
                        .HasForeignKey("LawID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Law");
                });

            modelBuilder.Entity("LegalMateAI.Domain.Entities.ChatbotLog", b =>
                {
                    b.HasOne("LegalMateAI.Domain.Entities.User", "User")
                        .WithMany("ChatbotLogs")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LegalMateAI.Domain.Entities.Clause", b =>
                {
                    b.HasOne("LegalMateAI.Domain.Entities.Articles", "Article")
                        .WithMany("Clauses")
                        .HasForeignKey("ArticleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("LegalMateAI.Domain.Entities.Consultation", b =>
                {
                    b.HasOne("LegalMateAI.Domain.Entities.Admin", "Admin")
                        .WithMany("AdminConsultations")
                        .HasForeignKey("AdminID");

                    b.HasOne("LegalMateAI.Domain.Entities.Lawyer", "Lawyer")
                        .WithMany("LawyerConsultations")
                        .HasForeignKey("LawyerID");

                    b.HasOne("LegalMateAI.Domain.Entities.User", "User")
                        .WithMany("UserConsultations")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Lawyer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LegalMateAI.Domain.Entities.IRDocuments", b =>
                {
                    b.HasOne("LegalMateAI.Domain.Entities.User", "User")
                        .WithMany("IRDocuments")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LegalMateAI.Domain.Entities.IRQueries", b =>
                {
                    b.HasOne("LegalMateAI.Domain.Entities.User", "User")
                        .WithMany("IRQueries")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LegalMateAI.Domain.Entities.IRQueryDocument", b =>
                {
                    b.HasOne("LegalMateAI.Domain.Entities.IRDocuments", "Document")
                        .WithMany("DocumentQueries")
                        .HasForeignKey("DocumentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LegalMateAI.Domain.Entities.IRQueries", "Query")
                        .WithMany("QueryDocuments")
                        .HasForeignKey("QueryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Query");
                });

            modelBuilder.Entity("LegalMateAI.Domain.Entities.LawUpdates", b =>
                {
                    b.HasOne("LegalMateAI.Domain.Entities.Law", "Law")
                        .WithMany("LawUpdates")
                        .HasForeignKey("LawID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Law");
                });

            modelBuilder.Entity("LegalMateAI.Domain.Entities.ModelResults", b =>
                {
                    b.HasOne("LegalMateAI.Domain.Entities.AIModels", "AIModel")
                        .WithMany("ModelResults")
                        .HasForeignKey("AIModelModelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AIModel");
                });

            modelBuilder.Entity("LegalMateAI.Domain.Entities.Notification", b =>
                {
                    b.HasOne("LegalMateAI.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LegalMateAI.Domain.Entities.UserContracts", b =>
                {
                    b.HasOne("LegalMateAI.Domain.Entities.ContractsTemplate", "Template")
                        .WithMany("Templates")
                        .HasForeignKey("TemplateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegalMateAI.Domain.Entities.User", "User")
                        .WithMany("UserContracts")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LegalMateAI.Domain.Entities.AIModels", b =>
                {
                    b.Navigation("ModelResults");
                });

            modelBuilder.Entity("LegalMateAI.Domain.Entities.Admin", b =>
                {
                    b.Navigation("AdminConsultations");

                    b.Navigation("AdminLogs");
                });

            modelBuilder.Entity("LegalMateAI.Domain.Entities.Articles", b =>
                {
                    b.Navigation("Clauses");
                });

            modelBuilder.Entity("LegalMateAI.Domain.Entities.ContractsTemplate", b =>
                {
                    b.Navigation("Templates");
                });

            modelBuilder.Entity("LegalMateAI.Domain.Entities.IRDocuments", b =>
                {
                    b.Navigation("DocumentQueries");
                });

            modelBuilder.Entity("LegalMateAI.Domain.Entities.IRQueries", b =>
                {
                    b.Navigation("QueryDocuments");
                });

            modelBuilder.Entity("LegalMateAI.Domain.Entities.Law", b =>
                {
                    b.Navigation("LawArticles");

                    b.Navigation("LawUpdates");
                });

            modelBuilder.Entity("LegalMateAI.Domain.Entities.Lawyer", b =>
                {
                    b.Navigation("LawyerConsultations");
                });

            modelBuilder.Entity("LegalMateAI.Domain.Entities.User", b =>
                {
                    b.Navigation("ChatbotLogs");

                    b.Navigation("IRDocuments");

                    b.Navigation("IRQueries");

                    b.Navigation("Notifications");

                    b.Navigation("UserConsultations");

                    b.Navigation("UserContracts");
                });
#pragma warning restore 612, 618
        }
    }
}
